language: r
cache: packages
notifications:
  slack: edmondsons:kgTokxui4ZzTsqdD19tCoozf
  email:
    on_success: change
    on_failure: change
r_packages:
- knitr
- covr
- drat
after_success:
- Rscript -e 'library("covr");codecov()'
before_install:
- openssl aes-256-cbc -K $encrypted_440eac6d6480_key -iv $encrypted_440eac6d6480_iv
  -in auth.json.enc -out auth.json -d
- openssl aes-256-cbc -K $encrypted_440eac6d6480_key -iv $encrypted_440eac6d6480_iv
  -in auth.json.enc -out tests/testthat/auth.json -d
env:
  global:
    secure: IOeDnUVWA5Z6ANOuG1d0LfaC21I9o7uuh8+gi2C7TYLzg9UqOBZF2PrmR+TK6fMyY/ZmeNEH+5sEqBAor0k7WYAOtbCTQBVz2HFLEAsjXmGBbHdeQunhQFWXs1iu1l/BbuQptIkSY3CewnpyhQ031vJwPBonMsLCUavxety1A34QYHO7z2go8jsihQGK12tWwGbaZo9Qw6nXOeL70LcU/y3VVkHGV+AYwa+7QIpmnZvdiyQXdfXPzkYceatn4B8HECOlkiwWTFFUiR2FVkiZG50ogYM5kjLM3ExIRfDNUpoDqgZe0Isoc5YFTuTseEGOrVF35S2DtKW5nb/eU1dtTuZ/pXc4POzWHR1cYPGvIqsUXagRcEPnCHYn6GexHtrniiP8IyAOcNGethh5GhqIOOx1zK80/ap2RaDHGtaMo2lEGe4vgsNasRYyO57dbQrVfYtpLS0HWuQ7CqPez0ZQbh0NlZbuTJzQEd6OqAaBRGxhDnkBAulsMrFfCLR01fdEAeWOeTO2XBsuFr+9bwbBTGqbaEnw/JJTC1YqFqyND6Iyfy3JbAQSm7+AnKXcT47dpSwkpme84u1t5DA14z2SkbVgcN7ZwM/0HsPGHjlt3RKS1HTF823cChFi09qqqjnDdIwetZDsSj95v7ceTmCsKulrKy695XSIF8F7xkn9nrY=
