language: r
cache: packages
notifications:
  slack: edmondsons:kgTokxui4ZzTsqdD19tCoozf
  email:
    on_success: change
    on_failure: change
r_packages:
- knitr
- covr
- drat
script:
- |
  R CMD build .
  travis_wait 40 R CMD check googleComputeEngineR*tar.gz
after_failure:
- find *Rcheck -name '*.fail' -print -exec cat '{}' \;
after_success:
- travis_wait 40 Rscript -e 'library("covr");codecov(line_exclusions = list("R/options.R",
  "R/utilities.R"))'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  drat.sh
before_install:
- openssl aes-256-cbc -K $encrypted_440eac6d6480_key -iv $encrypted_440eac6d6480_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- cp auth/auth.json auth.json
- cp auth.json tests/testthat/auth.json
- cp auth/travis-ssh-key tests/testthat/travis-ssh-key
- cp auth/travis-ssh-key.pub tests/testthat/travis-ssh-key.pub
- eval "$(ssh-agent -s)"
- ssh-add tests/testthat/travis-ssh-key
env:
  global:
  - secure: AfUqQSeIySgjKrOloUhvInzjOPhSJkLb5ahKrcQ4h8z5CmuHETC/X2QV9FFDHuxUDUUvA+JPP/tZvrUU1kJfhgEflzgV1mgnsJrTws1LQFjpzhaRUG8zSupFMzGUgX+z+kPu1rV1euTYvdNXVuj8PUVomaLR7bVPKgWYzVuyoVliyfApPIWm+IgDNClvOpCokm5lqdoM/vTnPwh5xaC8z8SK2xE0KcVgrqD53Y10KNs31/abVHGD+8Cdv6j7RElQZMfT1AWYW2auWfvTdeMZZAwr+Uq74c0yWwMq6iQLLPMCGegN7CLp0xWfZ76WfRijkvew8IWf/hCMbetFT2dqtS1vRbfgzzYrQQk1OQSf6bNlZSakwiNAje2enz1bs+41pNcNYBH9E56Jn1cmtKaIgdVBcNBvLe4lf3cAfouro7Adr9bZq+heVfVK4L7ZNCQEfEDewyOJCZXJSD+LmqCeT7hBN7yfoQuPTJ1DTfj++xzAgYZMB2i1mfgbAIiu9tOqkPO6T1oxtWcnrkvofTA0oWgSs8OZSO0ZUOcbHkIhMx8/EjJbw/8NJOI43vQj5xwpfzRAjTX65GdZdjxwuTYKVCPjsMcjwNcDDS49zQO7qfqtVET9ZA0QZP6k5LZugkD7y1+iTTAV+2exptmxcOdJzoWDpf12CkFu8phpOeiNJDI=
  - secure: e2Oe+uQwF6n8FkayMRi0f61vsdvHVBU+SX/SE0adVA4VoN7m68pIHDN4MlV3bHkYcT5IURFtX89T2Dk33aNlXxNZtaygQMZdcTEZjV1niivrOVsilyBqEVIYV2lA7660dae38Eud3YOKOfxM3SMXHCAlNGRZxZaoX5zcZr4OIsGp11Aun/6KmtbLuD2YrjF12KWvHlBUXdTbkVRWCfuRZAibO2TbubLQ0eVD7ak8WGXlLnJLMrONBCcTbVESyAlyweYL6zf00v8t3443CFnltZwOBVfZ+zZSF5lbNji45IXPWolBYWwnqqvfVpgAHUhN+OQ7cYV5tsiJaCIPiL75HZP2VVBQZRftmqHi9dXjrBicAOTYDr1Ciuv7EvTKs7Dba/L4q6hmMPLawgpqMD+LRw+gStLq/dKkUucykB1Fx0prxLUG8ZMHpMjiTC1/+aw4ziE982ZSQCnJ1Vjcs0dM5E52PRW/w2vcIw6X6Ob7keKhjaePAvhMpqxUd7Iunwau1TJ4jHi6Grd77gVUCCcJyOMvN4HnnQgfQcK/XY6KBDejNNCtJ24j/44r6vZhYktqvrrPOqT81g+ZQj3vdJuCyNNFXf76pXKjNGMQrEYPZJCZWpr8R2fbMuDuYkDaVD3Sgax9PjzBSo0DXSAe2563cFRSYDtnfnzllYlvOoNgeUA=
