language: r
cache: packages
notifications:
  slack: edmondsons:kgTokxui4ZzTsqdD19tCoozf
  email:
    on_success: change
    on_failure: change
r_packages:
- knitr
- covr
- drat
after_success:
- Rscript -e 'library("covr");codecov()'
before_install:
- openssl aes-256-cbc -K $encrypted_440eac6d6480_key -iv $encrypted_440eac6d6480_iv
  -in auth.json.enc -out auth.json -d
- openssl aes-256-cbc -K $encrypted_440eac6d6480_key -iv $encrypted_440eac6d6480_iv
  -in auth.json.enc -out tests/testthat/auth.json -d