#cloud-config

users:
- name: gcer
  uid: 2000

write_files:
- path: /home/gcer/build/Dockerfile
  permissions: 0644
  owner: root
  content: |
%s
    
runcmd:
- cd /home/gcer/build && docker build -t %s .
- /usr/share/google/dockercfg_update.sh
- docker push %s