#cloud-config

users:
- name: gcer
  uid: 2000

write_files:
- path: /etc/systemd/system/builddocker.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=Start Docker build service

    [Service]
    Type=oneshot
    RemainAferExit=yes
    Environment="HOME=/home/gcer"
    ExecStartPre=/usr/share/google/dockercfg_update.sh
    ExecStart=/usr/bin/docker build -t %s /home/gcer/build/
    ExecStart=/usr/bin/docker push %s

- path: /home/gcer/build/Dockerfile
  permissions: 0644
  owner: root
  content: |
%s

runcmd:
- systemctl daemon-reload
- systemctl start builddocker.service
