#cloud-config

users:
- name: gcer
  uid: 2000

write_files:
- path: /etc/gcer/startup.sh
  permissions: 0755
  owner: root
  content: |
    #!/bin/bash
    echo "Docker RStudio launch script"

    RSTUDIO_USER=$(curl http://metadata.google.internal/computeMetadata/v1/instance/attributes/rstudio_user -H "Metadata-Flavor: Google")
    RSTUDIO_PW=$(curl http://metadata.google.internal/computeMetadata/v1/instance/attributes/rstudio_pw -H "Metadata-Flavor: Google")
    RSTUDIO_DOCKER_IMAGE=$(curl http://metadata.google.internal/computeMetadata/v1/instance/attributes/rstudio_docker_image -H "Metadata-Flavor: Google")

    echo "Docker image: $RSTUDIO_DOCKER_IMAGE"

    docker run -p 80:8787 \
               -e ROOT=TRUE \
               -e USER=$RSTUDIO_USER -e PASSWORD=$RSTUDIO_PW \
               --name=rstudio \
               $RSTUDIO_DOCKER_IMAGE
                  
- path: /etc/systemd/system/custom-docker.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=Start Dynamic Docker image

    [Service]
    Restart=always
    Environment="HOME=/home/gcer"
    ExecStartPre=/usr/bin/docker-credential-gcr configure-docker
    ExecStart=/etc/gcer/startup.sh
    ExecStop=/usr/bin/docker stop %s

runcmd:
- systemctl daemon-reload
- systemctl start custom-docker.service