#cloud-config

users:
- name: gcer
  uid: 2000

write_files:
- path: /etc/systemd/system/custom-docker.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=Start Dynamic Docker image

    [Service]
    Restart=always
    Environment="HOME=/home/gcer"
    ExecStartPre=/usr/bin/docker-credential-gcr configure-docker
    ExecStart=/usr/bin/docker run --name=dynamic \
                                  %s
    ExecStop=/usr/bin/docker stop dynamic
    ExecStopPost=/usr/bin/docker rm dynamic
    
runcmd:
- systemctl daemon-reload
- systemctl start custom-docker.service