#cloud-config

users:
- name: cloudservice
  uid: 2000

write_files:
- path: /etc/systemd/system/cloudservice.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=R Base

    [Service]
    ExecStart=/usr/bin/docker run -u 2000 --name=rbase rocker/r-base R --save
    ExecStop=/usr/bin/docker stop rbase

runcmd:
- systemctl daemon-reload
- systemctl start cloudservice.service