#cloud-config

users:
- name: cloudservice
  uid: 2000

write_files:
- path: /etc/systemd/system/cloudservice.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=RStudio Server

    [Service]
    ExecStart=/usr/bin/docker run -u 2000 -p 8787:8787 -e ROOT=TRUE -e USER=%s -e PASSWORD=%s --name=rstudio rocker/rstudio
    ExecStop=/usr/bin/docker stop rstudio

runcmd:
- systemctl daemon-reload
- systemctl start cloudservice.service