#cloud-config

users:
- name: gcer
  uid: 2000

write_files:
- path: /etc/systemd/system/shinyserver.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=Shiny Server
    Requires=docker.service
    After=docker.service

    [Service]
    Restart=always
    Environment="HOME=/home/gcer"
    ExecStartPre=/usr/bin/docker-credential-gcr configure-docker
    ExecStart=/usr/bin/docker run --name=shinyserver \
                                  -p 80:3838 \
                                  %s
    ExecStop=/usr/bin/docker stop shinyserver
    ExecStopPost=/usr/bin/docker rm shinyserver

runcmd:
- systemctl daemon-reload
- systemctl start shinyserver.service